spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/foodgrid/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost