spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=3
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/api/v1/restaurant/**
          filters:
            - StripPrefix=3
            - RemoveRequestHeader=Cookie
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=3
            - RemoveRequestHeader=Cookie
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=3
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/api/v1/delivery/**
          filters:
            - StripPrefix=3
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=2
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/foodgrid/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    ip-address: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true