spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost