spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: http://user:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2
        - id: restaurant
          uri: http://restaurant:8082
          predicates:
            - Path=/api/v1/restaurant/**
          filters:
            - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: eureka