spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: http://user:8081
          predicates:
            - Path=/user/**
        - id: restaurant
          uri: http://restaurant:8082
          predicates:
            - Path=/restaurant/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST}