spring:
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**, /
          filters:
            - StripPrefix=1
        - id: restaurant
          uri: lb://restaurant
          predicates:
            - Path=/restaurant/**
          filters:
            - StripPrefix=1
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - StripPrefix=1
        - id: accounts
          uri: lb://accounts
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    ip-address: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true