spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 20000
        response-timeout: 50000
      routes:
        - id: user
          uri: http://user:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=3
        - id: restaurant
          uri: http://restaurant:8082
          predicates:
            - Path=/api/v1/restaurant/**
          filters:
            - StripPrefix=3
        - id: notification
          uri: http://notification:8083
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=3
        - id: order
          uri: http://order:8084
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=3
        - id: delivery
          uri: http://delivery:8085
          predicates:
            - Path=/api/v1/delivery/**
          filters:
            - StripPrefix=3
        - id: account
          uri: http://account:8086
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=2
        - id: frontend
          uri: http://frontend:8090
          predicates:
            - Path=/frontend/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: eureka