eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: eureka

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      repositories:
        enabled: true
  cloud:
    stream:
      function:
        defination: authentication
      bindings:
        authentication-in-0:
          destination: authentication
      kafka:
        binder:
          brokers:
            - kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"