eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/foodgrid-order}
      repositories:
        enabled: true
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
