eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    ip-address: ${spring.application.name}-service
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true

spring:
  data:
    mongodb:
      uri: mongodb://database:27017/foodgrid-restaurant
      repositories:
        enabled: true
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    packages:
      trust-all: true

management:
  endpoints:
    web:
      exposure:
        include: "*"